services:
  db:
    image: mysql:8.0
    container_name: vintage_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: VintageDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DataBase:/docker-entrypoint-initdb.d

  api:
    build: ./Backend
    container_name: vintage_api
    depends_on:
      db:
        condition: service_started
    environment:
      - ConnectionStrings__connection=Server=db;Port=3306;Database=VintageDB;User=user;Password=password;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  web:
    build: ./Frontend
    container_name: vintage_web
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  mysql_data:
